[package]
name = "healthscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.4.0"
chumsky = "0.9.3"
jaq = "1.3.0"
regex = "1.10.4"

[dev-dependencies]
expect-test = "1.5.0"
